// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FoodPreferences.proto

package com.tony.datastoresample;

public final class FoodPreferencesOuterClass {
  private FoodPreferencesOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_FoodPreferences_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_FoodPreferences_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025FoodPreferences.proto\"\355\001\n\017FoodPreferen" +
      "ces\022\'\n\004type\030\001 \001(\0162\031.FoodPreferences.Food" +
      "Type\022)\n\005taste\030\002 \001(\0162\032.FoodPreferences.Fo" +
      "odTaste\"@\n\010FoodType\022\024\n\020TYPE_UNSPECIFIED\020" +
      "\000\022\014\n\010TYPE_VEG\020\001\022\020\n\014TYPE_NON_VEG\020\002\"D\n\tFoo" +
      "dTaste\022\025\n\021TASTE_UNSPECIFIED\020\000\022\017\n\013TASTE_S" +
      "WEET\020\001\022\017\n\013TASTE_SPICY\020\002B\034\n\030com.tony.data" +
      "storesampleP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_FoodPreferences_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_FoodPreferences_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_FoodPreferences_descriptor,
        new java.lang.String[] { "Type", "Taste", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
