// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FoodPreferences.proto

package com.tony.datastoresample;

public interface FoodPreferencesOrBuilder extends
    // @@protoc_insertion_point(interface_extends:FoodPreferences)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>optional .FoodPreferences.FoodType type = 1;</code>
   */
  int getTypeValue();
  /**
   * <code>optional .FoodPreferences.FoodType type = 1;</code>
   */
  com.tony.datastoresample.FoodPreferences.FoodType getType();

  /**
   * <code>optional .FoodPreferences.FoodTaste taste = 2;</code>
   */
  int getTasteValue();
  /**
   * <code>optional .FoodPreferences.FoodTaste taste = 2;</code>
   */
  com.tony.datastoresample.FoodPreferences.FoodTaste getTaste();
}
