// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FoodPreferences.proto

package com.tony.datastoresample;

/**
 * Protobuf type {@code FoodPreferences}
 */
public  final class FoodPreferences extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:FoodPreferences)
    FoodPreferencesOrBuilder {
  // Use FoodPreferences.newBuilder() to construct.
  private FoodPreferences(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private FoodPreferences() {
    type_ = 0;
    taste_ = 0;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return com.google.protobuf.UnknownFieldSet.getDefaultInstance();
  }
  private FoodPreferences(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    int mutable_bitField0_ = 0;
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!input.skipField(tag)) {
              done = true;
            }
            break;
          }
          case 8: {
            int rawValue = input.readEnum();

            type_ = rawValue;
            break;
          }
          case 16: {
            int rawValue = input.readEnum();

            taste_ = rawValue;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.tony.datastoresample.FoodPreferencesOuterClass.internal_static_FoodPreferences_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.tony.datastoresample.FoodPreferencesOuterClass.internal_static_FoodPreferences_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.tony.datastoresample.FoodPreferences.class, com.tony.datastoresample.FoodPreferences.Builder.class);
  }

  /**
   * Protobuf enum {@code FoodPreferences.FoodType}
   */
  public enum FoodType
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>TYPE_UNSPECIFIED = 0;</code>
     */
    TYPE_UNSPECIFIED(0),
    /**
     * <code>TYPE_VEG = 1;</code>
     */
    TYPE_VEG(1),
    /**
     * <code>TYPE_NON_VEG = 2;</code>
     */
    TYPE_NON_VEG(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>TYPE_UNSPECIFIED = 0;</code>
     */
    public static final int TYPE_UNSPECIFIED_VALUE = 0;
    /**
     * <code>TYPE_VEG = 1;</code>
     */
    public static final int TYPE_VEG_VALUE = 1;
    /**
     * <code>TYPE_NON_VEG = 2;</code>
     */
    public static final int TYPE_NON_VEG_VALUE = 2;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static FoodType valueOf(int value) {
      return forNumber(value);
    }

    public static FoodType forNumber(int value) {
      switch (value) {
        case 0: return TYPE_UNSPECIFIED;
        case 1: return TYPE_VEG;
        case 2: return TYPE_NON_VEG;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<FoodType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        FoodType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<FoodType>() {
            public FoodType findValueByNumber(int number) {
              return FoodType.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.tony.datastoresample.FoodPreferences.getDescriptor().getEnumTypes().get(0);
    }

    private static final FoodType[] VALUES = values();

    public static FoodType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private FoodType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:FoodPreferences.FoodType)
  }

  /**
   * Protobuf enum {@code FoodPreferences.FoodTaste}
   */
  public enum FoodTaste
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>TASTE_UNSPECIFIED = 0;</code>
     */
    TASTE_UNSPECIFIED(0),
    /**
     * <code>TASTE_SWEET = 1;</code>
     */
    TASTE_SWEET(1),
    /**
     * <code>TASTE_SPICY = 2;</code>
     */
    TASTE_SPICY(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>TASTE_UNSPECIFIED = 0;</code>
     */
    public static final int TASTE_UNSPECIFIED_VALUE = 0;
    /**
     * <code>TASTE_SWEET = 1;</code>
     */
    public static final int TASTE_SWEET_VALUE = 1;
    /**
     * <code>TASTE_SPICY = 2;</code>
     */
    public static final int TASTE_SPICY_VALUE = 2;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static FoodTaste valueOf(int value) {
      return forNumber(value);
    }

    public static FoodTaste forNumber(int value) {
      switch (value) {
        case 0: return TASTE_UNSPECIFIED;
        case 1: return TASTE_SWEET;
        case 2: return TASTE_SPICY;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<FoodTaste>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        FoodTaste> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<FoodTaste>() {
            public FoodTaste findValueByNumber(int number) {
              return FoodTaste.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.tony.datastoresample.FoodPreferences.getDescriptor().getEnumTypes().get(1);
    }

    private static final FoodTaste[] VALUES = values();

    public static FoodTaste valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private FoodTaste(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:FoodPreferences.FoodTaste)
  }

  public static final int TYPE_FIELD_NUMBER = 1;
  private int type_;
  /**
   * <code>optional .FoodPreferences.FoodType type = 1;</code>
   */
  public int getTypeValue() {
    return type_;
  }
  /**
   * <code>optional .FoodPreferences.FoodType type = 1;</code>
   */
  public com.tony.datastoresample.FoodPreferences.FoodType getType() {
    com.tony.datastoresample.FoodPreferences.FoodType result = com.tony.datastoresample.FoodPreferences.FoodType.valueOf(type_);
    return result == null ? com.tony.datastoresample.FoodPreferences.FoodType.UNRECOGNIZED : result;
  }

  public static final int TASTE_FIELD_NUMBER = 2;
  private int taste_;
  /**
   * <code>optional .FoodPreferences.FoodTaste taste = 2;</code>
   */
  public int getTasteValue() {
    return taste_;
  }
  /**
   * <code>optional .FoodPreferences.FoodTaste taste = 2;</code>
   */
  public com.tony.datastoresample.FoodPreferences.FoodTaste getTaste() {
    com.tony.datastoresample.FoodPreferences.FoodTaste result = com.tony.datastoresample.FoodPreferences.FoodTaste.valueOf(taste_);
    return result == null ? com.tony.datastoresample.FoodPreferences.FoodTaste.UNRECOGNIZED : result;
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (type_ != com.tony.datastoresample.FoodPreferences.FoodType.TYPE_UNSPECIFIED.getNumber()) {
      output.writeEnum(1, type_);
    }
    if (taste_ != com.tony.datastoresample.FoodPreferences.FoodTaste.TASTE_UNSPECIFIED.getNumber()) {
      output.writeEnum(2, taste_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (type_ != com.tony.datastoresample.FoodPreferences.FoodType.TYPE_UNSPECIFIED.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, type_);
    }
    if (taste_ != com.tony.datastoresample.FoodPreferences.FoodTaste.TASTE_UNSPECIFIED.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(2, taste_);
    }
    memoizedSize = size;
    return size;
  }

  private static final long serialVersionUID = 0L;
  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.tony.datastoresample.FoodPreferences)) {
      return super.equals(obj);
    }
    com.tony.datastoresample.FoodPreferences other = (com.tony.datastoresample.FoodPreferences) obj;

    boolean result = true;
    result = result && type_ == other.type_;
    result = result && taste_ == other.taste_;
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptorForType().hashCode();
    hash = (37 * hash) + TYPE_FIELD_NUMBER;
    hash = (53 * hash) + type_;
    hash = (37 * hash) + TASTE_FIELD_NUMBER;
    hash = (53 * hash) + taste_;
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.tony.datastoresample.FoodPreferences parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.tony.datastoresample.FoodPreferences parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.tony.datastoresample.FoodPreferences parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.tony.datastoresample.FoodPreferences parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.tony.datastoresample.FoodPreferences parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.tony.datastoresample.FoodPreferences parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.tony.datastoresample.FoodPreferences parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.tony.datastoresample.FoodPreferences parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.tony.datastoresample.FoodPreferences parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.tony.datastoresample.FoodPreferences parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.tony.datastoresample.FoodPreferences prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code FoodPreferences}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:FoodPreferences)
      com.tony.datastoresample.FoodPreferencesOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.tony.datastoresample.FoodPreferencesOuterClass.internal_static_FoodPreferences_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.tony.datastoresample.FoodPreferencesOuterClass.internal_static_FoodPreferences_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.tony.datastoresample.FoodPreferences.class, com.tony.datastoresample.FoodPreferences.Builder.class);
    }

    // Construct using com.tony.datastoresample.FoodPreferences.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      type_ = 0;

      taste_ = 0;

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.tony.datastoresample.FoodPreferencesOuterClass.internal_static_FoodPreferences_descriptor;
    }

    public com.tony.datastoresample.FoodPreferences getDefaultInstanceForType() {
      return com.tony.datastoresample.FoodPreferences.getDefaultInstance();
    }

    public com.tony.datastoresample.FoodPreferences build() {
      com.tony.datastoresample.FoodPreferences result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public com.tony.datastoresample.FoodPreferences buildPartial() {
      com.tony.datastoresample.FoodPreferences result = new com.tony.datastoresample.FoodPreferences(this);
      result.type_ = type_;
      result.taste_ = taste_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.tony.datastoresample.FoodPreferences) {
        return mergeFrom((com.tony.datastoresample.FoodPreferences)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.tony.datastoresample.FoodPreferences other) {
      if (other == com.tony.datastoresample.FoodPreferences.getDefaultInstance()) return this;
      if (other.type_ != 0) {
        setTypeValue(other.getTypeValue());
      }
      if (other.taste_ != 0) {
        setTasteValue(other.getTasteValue());
      }
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.tony.datastoresample.FoodPreferences parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.tony.datastoresample.FoodPreferences) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private int type_ = 0;
    /**
     * <code>optional .FoodPreferences.FoodType type = 1;</code>
     */
    public int getTypeValue() {
      return type_;
    }
    /**
     * <code>optional .FoodPreferences.FoodType type = 1;</code>
     */
    public Builder setTypeValue(int value) {
      type_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional .FoodPreferences.FoodType type = 1;</code>
     */
    public com.tony.datastoresample.FoodPreferences.FoodType getType() {
      com.tony.datastoresample.FoodPreferences.FoodType result = com.tony.datastoresample.FoodPreferences.FoodType.valueOf(type_);
      return result == null ? com.tony.datastoresample.FoodPreferences.FoodType.UNRECOGNIZED : result;
    }
    /**
     * <code>optional .FoodPreferences.FoodType type = 1;</code>
     */
    public Builder setType(com.tony.datastoresample.FoodPreferences.FoodType value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      type_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>optional .FoodPreferences.FoodType type = 1;</code>
     */
    public Builder clearType() {
      
      type_ = 0;
      onChanged();
      return this;
    }

    private int taste_ = 0;
    /**
     * <code>optional .FoodPreferences.FoodTaste taste = 2;</code>
     */
    public int getTasteValue() {
      return taste_;
    }
    /**
     * <code>optional .FoodPreferences.FoodTaste taste = 2;</code>
     */
    public Builder setTasteValue(int value) {
      taste_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>optional .FoodPreferences.FoodTaste taste = 2;</code>
     */
    public com.tony.datastoresample.FoodPreferences.FoodTaste getTaste() {
      com.tony.datastoresample.FoodPreferences.FoodTaste result = com.tony.datastoresample.FoodPreferences.FoodTaste.valueOf(taste_);
      return result == null ? com.tony.datastoresample.FoodPreferences.FoodTaste.UNRECOGNIZED : result;
    }
    /**
     * <code>optional .FoodPreferences.FoodTaste taste = 2;</code>
     */
    public Builder setTaste(com.tony.datastoresample.FoodPreferences.FoodTaste value) {
      if (value == null) {
        throw new NullPointerException();
      }
      
      taste_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>optional .FoodPreferences.FoodTaste taste = 2;</code>
     */
    public Builder clearTaste() {
      
      taste_ = 0;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return this;
    }


    // @@protoc_insertion_point(builder_scope:FoodPreferences)
  }

  // @@protoc_insertion_point(class_scope:FoodPreferences)
  private static final com.tony.datastoresample.FoodPreferences DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.tony.datastoresample.FoodPreferences();
  }

  public static com.tony.datastoresample.FoodPreferences getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<FoodPreferences>
      PARSER = new com.google.protobuf.AbstractParser<FoodPreferences>() {
    public FoodPreferences parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
        return new FoodPreferences(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<FoodPreferences> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<FoodPreferences> getParserForType() {
    return PARSER;
  }

  public com.tony.datastoresample.FoodPreferences getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

